In [1]:
import numpy as np
A = np.array([1,2,3,4])
np.ndim(A)


1

In [2]:
A.shape


(4,)

In [3]:
A = np.array([[1,2,3],[2,4,6],[3,6,9]])
B = np.array([10,20,30])
np.dot(A,B)

array([140, 280, 420])

In [4]:
X = np.array([0,0,1])
W1 = np.array([[2,2,-1],[2,2,0],[0,-1,-1]])
W2 = np.array([[2,2,-1],[-1,0,0],[2,-1,2]])
W3 = np.array([[2,-1,0],[-1,-1,0],[2,0,0]])

In [5]:
Y = np.dot(W3, np.dot(W2, np.dot(W1,X)))

In [6]:
Y

array([-3,  0, -2])

In [7]:
Y = np.dot(np.dot(np.dot(W3,W2),W1),X)
Y

array([-3,  0, -2])

In [8]:
 def sigmoid(x):
        return 1/(1+np.exp(-x))

In [9]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5],
              [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])


In [10]:
A1 = np.dot(X,W1) + B1
print(A1)

[0.3 0.7 1.1]


In [11]:
Z1 = sigmoid(A1)
print(Z1)

[0.57444252 0.66818777 0.75026011]


In [17]:
W2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2 = np.array([0.1,0.2])

A2 = np.dot(Z1,W2) + B2
Z2 = sigmoid(A2)
print(Z2)

[0.62624937 0.7710107 ]


In [21]:
def identity_function(x):
    return x

W3 = np.array([[0.1,0.3],[0.2,0.4]])
B3 = np.array([0.1,0.2])
A3 = np.dot(Z2,W3) + B3
Y = identity_function(A3)
print(Y)

[0.31682708 0.69627909]
