In [21]:
import numpy as np
import tensorflow.compat.v1 as tf #downgrade tensorflow to 1.0
tf.disable_v2_behavior()
#slicing
nums = [0,1,2,3,4]
print(nums)
print(nums[2:4])
print(nums[2:])
print(nums[:2])
print(nums[:])
print(nums[:-1])
nums[2:4] = [8,9]
print(nums)

b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b[:,1]) #whole list but first column

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]
[ 2  6 10]


In [22]:
xy = np.loadtxt('DeepLearningZeroToAll-master\DeepLearningZeroToAll-master/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1] #from whole data except the last column
y_data = xy[:, [-1]] #from whole only the last column 

#Make sure the shape and data are OK
#print(x_data.shape, x_data, len(x_data))
#print(y_data.shape, y_data)

In [25]:
#placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

#Hypothesis
hypothesis = tf.matmul(X, W) + b

#Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

#Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

#Launch the graph in a session
sess = tf.Session()
#Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())
#Set up feed_dict variables inside the loop
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val,
             "\nPrediction:\n", hy_val)
        
#Ask my score

print("Your score will be: ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be: ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

0 Cost:  88098.16 
Prediction:
 [[-131.07263 ]
 [-146.08086 ]
 [-149.96878 ]
 [-162.543   ]
 [-109.06639 ]
 [ -77.57835 ]
 [-123.50003 ]
 [ -94.51997 ]
 [-132.75977 ]
 [-120.01761 ]
 [-116.3716  ]
 [-109.2973  ]
 [-155.61232 ]
 [-129.66287 ]
 [-122.24605 ]
 [-148.51703 ]
 [-120.878265]
 [-150.50241 ]
 [-150.24168 ]
 [-135.46217 ]
 [-143.57504 ]
 [-136.9239  ]
 [-138.07845 ]
 [-133.75188 ]
 [-153.63246 ]]
10 Cost:  31.332014 
Prediction:
 [[146.04941]
 [186.96269]
 [178.20078]
 [194.85788]
 [144.92625]
 [109.6754 ]
 [144.03496]
 [103.8262 ]
 [178.48505]
 [168.26654]
 [141.37578]
 [144.83287]
 [183.43228]
 [152.18123]
 [146.5139 ]
 [189.44614]
 [147.53217]
 [170.57265]
 [172.99382]
 [153.75986]
 [170.14789]
 [175.51701]
 [161.03452]
 [145.65372]
 [191.5339 ]]
20 Cost:  27.01391 
Prediction:
 [[147.97955]
 [189.25061]
 [180.47159]
 [197.33064]
 [146.66351]
 [110.95196]
 [145.89438]
 [105.21745]
 [180.61545]
 [170.23624]
 [143.15805]
 [146.576  ]
 [185.7781 ]
 [154.12958]
 [148.37706]
 [19

 [[148.42435]
 [188.90176]
 [180.58368]
 [197.44614]
 [146.18326]
 [110.48453]
 [146.21906]
 [105.81735]
 [180.0765 ]
 [169.64359]
 [143.21417]
 [146.23901]
 [185.8843 ]
 [154.16684]
 [148.57056]
 [191.4921 ]
 [149.14713]
 [173.40187]
 [175.47351]
 [156.07646]
 [172.58014]
 [177.38832]
 [163.43294]
 [148.0319 ]
 [193.69   ]]
320 Cost:  23.871428 
Prediction:
 [[148.43849]
 [188.88972]
 [180.58678]
 [197.44939]
 [146.16695]
 [110.46893]
 [146.22946]
 [105.83706]
 [180.05835]
 [169.62389]
 [143.21567]
 [146.22762]
 [185.8871 ]
 [154.16737]
 [148.57666]
 [191.48245]
 [149.13876]
 [173.421  ]
 [175.48067]
 [156.086  ]
 [172.58821]
 [177.37877]
 [163.44313]
 [148.04543]
 [193.68214]]
330 Cost:  23.775742 
Prediction:
 [[148.45258]
 [188.87772]
 [180.58989]
 [197.45264]
 [146.15071]
 [110.45338]
 [146.23985]
 [105.8567 ]
 [180.04027]
 [169.6043 ]
 [143.21715]
 [146.21628]
 [185.8899 ]
 [154.1679 ]
 [148.58275]
 [191.47284]
 [149.1304 ]
 [173.4401 ]
 [175.48781]
 [156.0955 ]
 [172.59627]
 [17

620 Cost:  21.224644 
Prediction:
 [[148.84142 ]
 [188.54433 ]
 [180.67412 ]
 [197.5433  ]
 [145.69823 ]
 [110.024574]
 [146.53093 ]
 [106.408226]
 [179.54166 ]
 [169.06856 ]
 [143.2599  ]
 [145.90468 ]
 [185.96321 ]
 [154.17555 ]
 [148.75545 ]
 [191.20772 ]
 [148.89015 ]
 [173.9746  ]
 [175.68114 ]
 [156.35503 ]
 [172.82303 ]
 [177.10701 ]
 [163.7376  ]
 [148.42482 ]
 [193.45451 ]]
630 Cost:  21.143948 
Prediction:
 [[148.85416 ]
 [188.5333  ]
 [180.67685 ]
 [197.54631 ]
 [145.68326 ]
 [110.01053 ]
 [146.54062 ]
 [106.426636]
 [179.52533 ]
 [169.05115 ]
 [143.26135 ]
 [145.89453 ]
 [185.96548 ]
 [154.17558 ]
 [148.76126 ]
 [191.19902 ]
 [148.88194 ]
 [173.99237 ]
 [175.68735 ]
 [156.36343 ]
 [172.83063 ]
 [177.09842 ]
 [163.74704 ]
 [148.43661 ]
 [193.44722 ]]
640 Cost:  21.063698 
Prediction:
 [[148.86687 ]
 [188.52234 ]
 [180.67955 ]
 [197.5493  ]
 [145.66832 ]
 [109.99653 ]
 [146.55031 ]
 [106.444984]
 [179.50902 ]
 [169.03383 ]
 [143.2628  ]
 [145.88438 ]
 [185.96776 ]
 [154.17561

 [193.24281]]
930 Cost:  18.92256 
Prediction:
 [[149.21758]
 [188.21748]
 [180.75323]
 [197.63292]
 [145.25243]
 [109.61024]
 [146.82185]
 [106.95988]
 [179.05977]
 [168.56029]
 [143.30432]
 [145.6061 ]
 [186.02696]
 [154.17027]
 [148.93175]
 [190.95157]
 [148.6388 ]
 [174.50674]
 [175.86128]
 [156.6012 ]
 [173.05113]
 [176.85393]
 [164.02003]
 [148.76794]
 [193.23602]]
940 Cost:  18.854786 
Prediction:
 [[149.22906]
 [188.20741]
 [180.75562]
 [197.63571]
 [145.23865]
 [109.59758]
 [146.8309 ]
 [106.97706]
 [179.04504]
 [168.5449 ]
 [143.30573]
 [145.59702]
 [186.02881]
 [154.16989]
 [148.93729]
 [190.94373]
 [148.6308 ]
 [174.52325]
 [175.86667]
 [156.60864]
 [173.05826]
 [176.84622]
 [164.02878]
 [148.77826]
 [193.22925]]
950 Cost:  18.787352 
Prediction:
 [[149.24055]
 [188.19737]
 [180.75798]
 [197.63847]
 [145.22493]
 [109.58495]
 [146.83992]
 [106.99419]
 [179.03035]
 [168.52959]
 [143.30714]
 [145.58797]
 [186.03061]
 [154.16951]
 [148.94283]
 [190.93593]
 [148.62279]
 [174.539

1220 Cost:  17.10188 
Prediction:
 [[149.53629]
 [187.93698]
 [180.81827]
 [197.71048]
 [144.86795]
 [109.25961]
 [147.0762 ]
 [107.44249]
 [178.65193]
 [168.13812]
 [143.34457]
 [145.35556]
 [186.07498]
 [154.15509]
 [149.08888]
 [190.73485]
 [148.40993]
 [174.97028]
 [176.00815]
 [156.80566]
 [173.25175]
 [176.6401 ]
 [164.26553]
 [149.0495 ]
 [193.04596]]
1230 Cost:  17.044165 
Prediction:
 [[149.54675]
 [187.92772]
 [180.82039]
 [197.71306]
 [144.85521]
 [109.24812]
 [147.08467]
 [107.45858]
 [178.63857]
 [168.1244 ]
 [143.34593]
 [145.34738]
 [186.07646]
 [154.15443]
 [149.09418]
 [190.72775]
 [148.40216]
 [174.98569]
 [176.01286]
 [156.81232]
 [173.25847]
 [176.63309]
 [164.27371]
 [149.05861]
 [193.03963]]
1240 Cost:  16.986792 
Prediction:
 [[149.55716 ]
 [187.91847 ]
 [180.82245 ]
 [197.71562 ]
 [144.84251 ]
 [109.23665 ]
 [147.09311 ]
 [107.474625]
 [178.62521 ]
 [168.11075 ]
 [143.34729 ]
 [145.33923 ]
 [186.07791 ]
 [154.15373 ]
 [149.09944 ]
 [190.72066 ]
 [148.39438 ]
 [1

1530 Cost:  15.45312 
Prediction:
 [[149.84511 ]
 [187.6617  ]
 [180.87938 ]
 [197.78719 ]
 [144.48888 ]
 [108.920235]
 [147.33015 ]
 [107.92468 ]
 [178.25713 ]
 [167.73708 ]
 [143.38603 ]
 [145.11507 ]
 [186.11574 ]
 [154.13017 ]
 [149.24857 ]
 [190.52512 ]
 [148.17293 ]
 [175.43153 ]
 [176.14488 ]
 [156.99988 ]
 [173.45317 ]
 [176.4334  ]
 [164.50938 ]
 [149.31361 ]
 [192.85701 ]]
1540 Cost:  15.404455 
Prediction:
 [[149.85458]
 [187.65323]
 [180.88121]
 [197.78955]
 [144.47717]
 [108.90986]
 [147.33804]
 [107.93968]
 [178.24504]
 [167.72495]
 [143.38733]
 [145.10774]
 [186.11688]
 [154.12924]
 [149.25357]
 [190.5187 ]
 [148.16544]
 [175.44585]
 [176.14899]
 [157.00577]
 [173.45944]
 [176.42706]
 [164.51697]
 [149.32155]
 [192.85117]]
1550 Cost:  15.356073 
Prediction:
 [[149.86398]
 [187.64476]
 [180.88304]
 [197.7919 ]
 [144.46547]
 [108.89951]
 [147.34592]
 [107.95464]
 [178.233  ]
 [167.71284]
 [143.38863]
 [145.10045]
 [186.11803]
 [154.1283 ]
 [149.25858]
 [190.51231]
 [148.15

1800 Cost:  14.228581 
Prediction:
 [[150.0899 ]
 [187.44093]
 [180.92638]
 [197.84915]
 [144.18349]
 [108.65155]
 [147.53716]
 [108.31792]
 [177.9445 ]
 [167.42537]
 [143.42078]
 [144.92622]
 [186.14368]
 [154.10265]
 [149.3808 ]
 [190.35912]
 [147.97356]
 [175.80635]
 [176.2491 ]
 [157.15086]
 [173.61815]
 [176.26997]
 [164.70723]
 [149.51628]
 [192.70369]]
1810 Cost:  14.186597 
Prediction:
 [[150.09857]
 [187.43306]
 [180.92801]
 [197.85136]
 [144.1726 ]
 [108.64205]
 [147.54457]
 [108.33204]
 [177.93344]
 [167.41443]
 [143.42203]
 [144.91956]
 [186.14459]
 [154.10156]
 [149.38556]
 [190.35324]
 [147.96628]
 [175.81976]
 [176.25272]
 [157.15613]
 [173.62408]
 [176.26419]
 [164.7143 ]
 [149.52335]
 [192.69818]]
1820 Cost:  14.144837 
Prediction:
 [[150.1072 ]
 [187.42522]
 [180.92963]
 [197.85356]
 [144.16173]
 [108.63257]
 [147.55196]
 [108.3461 ]
 [177.92241]
 [167.40355]
 [143.4233 ]
 [144.91292]
 [186.14548]
 [154.10042]
 [149.39034]
 [190.34737]
 [147.95903]
 [175.83315]
 [176.