In [7]:
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()

In [9]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

#placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

#cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
#Minimize. Need a very samll learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

#launch the graph in a session
sess = tf.Session()
#Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict ={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction: \n", hy_val)

0 Cost:  11008.156 
Prediction: 
 [61.850574 70.47283  71.786255 76.36537  53.825596]
10 Cost:  5.6594114 
Prediction: 
 [154.63176 182.00586 181.67284 196.03021 138.90053]
20 Cost:  5.5301466 
Prediction: 
 [154.90355 182.34946 182.00255 196.39038 139.1659 ]
30 Cost:  5.501806 
Prediction: 
 [154.89543 182.35658 182.00081 196.38957 139.1746 ]
40 Cost:  5.4735317 
Prediction: 
 [154.88652 182.36273 181.99806 196.38771 139.18257]
50 Cost:  5.445526 
Prediction: 
 [154.87762 182.36879 181.99532 196.3858  139.19046]
60 Cost:  5.4175944 
Prediction: 
 [154.86874 182.37488 181.9926  196.38393 139.19836]
70 Cost:  5.389791 
Prediction: 
 [154.85988 182.38095 181.98987 196.38203 139.20624]
80 Cost:  5.3621993 
Prediction: 
 [154.85107 182.38701 181.98717 196.3802  139.2141 ]
90 Cost:  5.334764 
Prediction: 
 [154.84225 182.39299 181.98444 196.37833 139.22191]
100 Cost:  5.307479 
Prediction: 
 [154.83348 182.399   181.98175 196.37646 139.2297 ]
110 Cost:  5.2802935 
Prediction: 
 [154.82474 1

1250 Cost:  2.9756634 
Prediction: 
 [153.96642 182.99232 181.71461 196.19414 139.9992 ]
1260 Cost:  2.9611049 
Prediction: 
 [153.95999 182.9967  181.71263 196.19278 140.00488]
1270 Cost:  2.946622 
Prediction: 
 [153.9536  183.00108 181.71066 196.19145 140.01056]
1280 Cost:  2.9321895 
Prediction: 
 [153.94724 183.00548 181.70871 196.19014 140.01625]
1290 Cost:  2.9178462 
Prediction: 
 [153.94083 183.00981 181.70673 196.1888  140.02187]
1300 Cost:  2.9035778 
Prediction: 
 [153.9345  183.01418 181.70474 196.18747 140.02748]
1310 Cost:  2.8894048 
Prediction: 
 [153.92815 183.0185  181.7028  196.18616 140.0331 ]
1320 Cost:  2.8752823 
Prediction: 
 [153.92181 183.02283 181.70085 196.18483 140.03868]
1330 Cost:  2.861246 
Prediction: 
 [153.91551 183.02715 181.69891 196.18353 140.04427]
1340 Cost:  2.8472939 
Prediction: 
 [153.90924 183.03145 181.69698 196.18222 140.04984]
1350 Cost:  2.8334138 
Prediction: 
 [153.90295 183.03572 181.69505 196.18091 140.05539]
1360 Cost:  2.8195987 


Input이 늘어날 수록 코드가 길어지고 비효율적이게 된다. 그래서 사용하는 것이 Matrix

In [13]:
x_data = [[73., 80., 75.], [93., 88., 93.],
         [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

#placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

#Hypothesis
hypothesis = tf.matmul(X, W) + b
#cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
#Minimize. Need a very samll learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

#launch the graph in a session
sess = tf.Session()
#Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())
for step in range(5001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict ={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction: \n", hy_val)

0 Cost:  151.18451 
Prediction: 
 [[159.49107]
 [199.45462]
 [192.97713]
 [207.19412]
 [156.04123]]
10 Cost:  7.4877334 
Prediction: 
 [[148.89743]
 [186.70412]
 [180.423  ]
 [193.52249]
 [146.31181]]
20 Cost:  7.453084 
Prediction: 
 [[148.87465]
 [186.65907]
 [180.38777]
 [193.48364]
 [146.27348]]
30 Cost:  7.41989 
Prediction: 
 [[148.8839 ]
 [186.65254]
 [180.39047]
 [193.48605]
 [146.26451]]
40 Cost:  7.3869066 
Prediction: 
 [[148.89319]
 [186.64612]
 [180.39325]
 [193.4886 ]
 [146.25568]]
50 Cost:  7.3540907 
Prediction: 
 [[148.90244]
 [186.63972]
 [180.39603]
 [193.49112]
 [146.24683]]
60 Cost:  7.32144 
Prediction: 
 [[148.91167]
 [186.63335]
 [180.39877]
 [193.49364]
 [146.238  ]]
70 Cost:  7.2889833 
Prediction: 
 [[148.92088]
 [186.62698]
 [180.40154]
 [193.49615]
 [146.22923]]
80 Cost:  7.256677 
Prediction: 
 [[148.93007]
 [186.62062]
 [180.40427]
 [193.49864]
 [146.22046]]
90 Cost:  7.224553 
Prediction: 
 [[148.93922]
 [186.61429]
 [180.40701]
 [193.50114]
 [146.21172]

1130 Cost:  4.6650577 
Prediction: 
 [[149.76514]
 [186.04272]
 [180.65317]
 [193.7324 ]
 [145.41684]]
1140 Cost:  4.646668 
Prediction: 
 [[149.77196]
 [186.038  ]
 [180.65521]
 [193.73438]
 [145.41019]]
1150 Cost:  4.6283536 
Prediction: 
 [[149.7788 ]
 [186.03326]
 [180.65723]
 [193.73636]
 [145.40358]]
1160 Cost:  4.6101594 
Prediction: 
 [[149.78558]
 [186.02853]
 [180.65926]
 [193.73831]
 [145.39697]]
1170 Cost:  4.5920544 
Prediction: 
 [[149.79236]
 [186.02385]
 [180.66124]
 [193.74026]
 [145.39038]]
1180 Cost:  4.5740256 
Prediction: 
 [[149.79912]
 [186.01918]
 [180.66328]
 [193.74225]
 [145.3838 ]]
1190 Cost:  4.556119 
Prediction: 
 [[149.80585]
 [186.01448]
 [180.66527]
 [193.74417]
 [145.37724]]
1200 Cost:  4.538287 
Prediction: 
 [[149.81259]
 [186.00986]
 [180.66727]
 [193.74615]
 [145.37073]]
1210 Cost:  4.520547 
Prediction: 
 [[149.81927]
 [186.00519]
 [180.66925]
 [193.74808]
 [145.36418]]
1220 Cost:  4.502887 
Prediction: 
 [[149.82599]
 [186.00055]
 [180.67123]
 [

2270 Cost:  3.0819702 
Prediction: 
 [[150.43329]
 [185.57895]
 [180.85052]
 [193.93195]
 [144.7604 ]]
2280 Cost:  3.0718505 
Prediction: 
 [[150.43826]
 [185.57549]
 [180.852  ]
 [193.93349]
 [144.75548]]
2290 Cost:  3.0617297 
Prediction: 
 [[150.44324]
 [185.57205]
 [180.85347]
 [193.93504]
 [144.75053]]
2300 Cost:  3.0517123 
Prediction: 
 [[150.44815]
 [185.5686 ]
 [180.85489]
 [193.93657]
 [144.74562]]
2310 Cost:  3.0417087 
Prediction: 
 [[150.45308]
 [185.56519]
 [180.85635]
 [193.93813]
 [144.7407 ]]
2320 Cost:  3.0318053 
Prediction: 
 [[150.45798]
 [185.56177]
 [180.85777]
 [193.93964]
 [144.73582]]
2330 Cost:  3.0218918 
Prediction: 
 [[150.46289]
 [185.55835]
 [180.85924]
 [193.94118]
 [144.73093]]
2340 Cost:  3.0120692 
Prediction: 
 [[150.46776]
 [185.55496]
 [180.86066]
 [193.9427 ]
 [144.72606]]
2350 Cost:  3.0023043 
Prediction: 
 [[150.47263]
 [185.55159]
 [180.86208]
 [193.94421]
 [144.7212 ]]
2360 Cost:  2.992543 
Prediction: 
 [[150.47748]
 [185.54819]
 [180.86351

3410 Cost:  2.2041423 
Prediction: 
 [[150.91771]
 [185.24127]
 [180.9918 ]
 [194.08931]
 [144.27084]]
3420 Cost:  2.1984634 
Prediction: 
 [[150.92131]
 [185.23878]
 [180.99284]
 [194.09055]
 [144.26715]]
3430 Cost:  2.1928153 
Prediction: 
 [[150.92488]
 [185.23624]
 [180.99388]
 [194.09175]
 [144.26344]]
3440 Cost:  2.1871753 
Prediction: 
 [[150.92845]
 [185.23376]
 [180.9949 ]
 [194.093  ]
 [144.25977]]
3450 Cost:  2.1815968 
Prediction: 
 [[150.93202]
 [185.23128]
 [180.99596]
 [194.09422]
 [144.2561 ]]
3460 Cost:  2.1760402 
Prediction: 
 [[150.93556]
 [185.2288 ]
 [180.99696]
 [194.09543]
 [144.25244]]
3470 Cost:  2.170498 
Prediction: 
 [[150.93912]
 [185.22632]
 [180.99799]
 [194.09665]
 [144.2488 ]]
3480 Cost:  2.164997 
Prediction: 
 [[150.94264]
 [185.22385]
 [180.99901]
 [194.09787]
 [144.24516]]
3490 Cost:  2.1595232 
Prediction: 
 [[150.94617]
 [185.22139]
 [181.00003]
 [194.09908]
 [144.24153]]
3500 Cost:  2.1540725 
Prediction: 
 [[150.94968]
 [185.21895]
 [181.00105]

4570 Cost:  1.701301 
Prediction: 
 [[151.27255]
 [184.99251]
 [181.09344]
 [194.21742]
 [143.89844]]
4580 Cost:  1.698073 
Prediction: 
 [[151.2751 ]
 [184.99069]
 [181.09418]
 [194.21841]
 [143.89566]]
4590 Cost:  1.6948674 
Prediction: 
 [[151.2777 ]
 [184.9889 ]
 [181.0949 ]
 [194.2194 ]
 [143.89293]]
4600 Cost:  1.6916815 
Prediction: 
 [[151.28023]
 [184.98709]
 [181.09563]
 [194.22038]
 [143.89017]]
4610 Cost:  1.6884995 
Prediction: 
 [[151.28279]
 [184.9853 ]
 [181.09634]
 [194.22137]
 [143.88744]]
4620 Cost:  1.6853149 
Prediction: 
 [[151.28532]
 [184.98352]
 [181.09705]
 [194.22235]
 [143.88467]]
4630 Cost:  1.6821814 
Prediction: 
 [[151.28787]
 [184.98175]
 [181.09778]
 [194.22333]
 [143.88196]]
4640 Cost:  1.6790482 
Prediction: 
 [[151.29037]
 [184.97995]
 [181.09846]
 [194.2243 ]
 [143.87924]]
4650 Cost:  1.6759113 
Prediction: 
 [[151.29291]
 [184.97818]
 [181.0992 ]
 [194.2253 ]
 [143.87651]]
4660 Cost:  1.6728108 
Prediction: 
 [[151.29541]
 [184.97641]
 [181.0999 ]